blank_issues_enabled: false
contact_links:
  - name: RPCSX Troubleshooting/Support 
    url: https://discord.gg/t6dzA4wUdG
    about: For support and technical issues, please come to our Discord server.
